-- MySQL Script generated by MySQL Workbench
-- Fri Apr 15 16:35:05 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pollution
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pollution
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pollution` DEFAULT CHARACTER SET utf8 ;
USE `pollution` ;

-- -----------------------------------------------------
-- Table `pollution`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pollution`.`location` (
  `Id` INT NOT NULL,
  `Location` VARCHAR(100) NOT NULL,
  `geo_point_2d` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pollution`.`airquality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pollution`.`airquality` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Date Time` DATETIME NOT NULL,
  `NOx` DOUBLE NULL DEFAULT NULL,
  `NO2` DOUBLE NULL DEFAULT NULL,
  `NO` DOUBLE NULL DEFAULT NULL,
  `SiteID` INT NOT NULL,
  `PM10` DOUBLE NULL DEFAULT NULL,
  `NVPM10` DOUBLE NULL DEFAULT NULL,
  `VPM10` DOUBLE NULL DEFAULT NULL,
  `NVPM2.5` DOUBLE NULL DEFAULT NULL,
  `PM2.5` DOUBLE NULL DEFAULT NULL,
  `VPM2.5` DOUBLE NULL DEFAULT NULL,
  `CO` DOUBLE NULL DEFAULT NULL,
  `O3` DOUBLE NULL DEFAULT NULL,
  `SO2` DOUBLE NULL DEFAULT NULL,
  `Temperature` FLOAT NULL DEFAULT NULL,
  `RH` FLOAT NULL DEFAULT NULL,
  `Air Pressure` DOUBLE NULL DEFAULT NULL,
  `DateStart` DATETIME NULL DEFAULT NULL,
  `DateEnd` DATETIME NULL DEFAULT NULL,
  `Current` VARCHAR(5) NULL DEFAULT NULL,
  `Instrument Type` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_AirQuality_Location_idx` (`SiteID` ASC) VISIBLE,
  CONSTRAINT `fk_Air Quality_Location`
    FOREIGN KEY (`SiteID`)
    REFERENCES `pollution`.`location` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
